// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gas-td-importer/td/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mock/data",
				Handler: MockDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/gas/list",
				Handler: GasListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gas/add",
				Handler: GasAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gas/batch/add",
				Handler: GasBatchAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gas/multi/add",
				Handler: GasMultiAddHandler(serverCtx),
			},
		},
	)
}
