// Code generated by goctl. DO NOT EDIT.
package types

type Gas struct {
	Ts     string  `json:"ts"`
	Value  float64 `json:"value"`
	Point  string  `json:"point"`
	PName  string  `json:"pname"`
	Unit   string  `json:"unit"`
	Region string  `json:"region"`
}

type GasListRequest struct {
	TsStart string `json:"ts_start,optional"`
	TsEnd   string `json:"ts_end,optional"`
}

type GasListReply struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	List    []*Gas `json:"list"`
}

type GasAddRequest struct {
	Ts     string  `json:"ts"`
	Value  float64 `json:"value"`
	Point  string  `json:"point"`
	PName  string  `json:"pname"`
	Unit   string  `json:"unit"`
	Region string  `json:"region"`
}

type GasAddReply struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Num     int64  `json:"num"`
}

type GasBatchAddRequest struct {
	Tss    []string  `json:"tss"`
	Values []float64 `json:"values"`
	Point  string    `json:"point"`
	PName  string    `json:"pname"`
	Unit   string    `json:"unit"`
	Region string    `json:"region"`
}

type GasBatchAddReply struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Num     int64  `json:"num"`
}
