// Code generated by goctl. DO NOT EDIT.
package types

type GasAddRequest struct {
	Ts     string  `json:"ts"`
	Value  float64 `json:"value"`
	Point  string  `json:"point"`
	PName  string  `json:"pname"`
	Unit   string  `json:"unit"`
	Region string  `json:"region"`
}

type GasAddReply struct {
	Code    int    `json:"code"`
	Num     int64  `json:"num"`
	Message string `json:"message"`
}

type GasBatchAddRequest struct {
	Tss    []string  `json:"tss"`
	Values []float64 `json:"values"`
	Point  string    `json:"point"`
	PName  string    `json:"pname"`
	Unit   string    `json:"unit"`
	Region string    `json:"region"`
}

type GasBatchAddReply struct {
	Code    int    `json:"code"`
	Num     int64  `json:"num"`
	Message string `json:"message"`
}
