// Code generated by goctl. DO NOT EDIT.
package types

type GasAddRequest struct {
	Ts     string  `json:"ts"`
	Point  string  `json:"point"`
	PName  string  `json:"pname"`
	Unit   string  `json:"unit"`
	Region string  `json:"region"`
	Value  float64 `json:"value"`
}

type GasAddReply struct {
	Num     int64  `json:"num"`
	Message string `json:"message"`
}

type GasBatchAddRequest struct {
	Ts       string    `json:"ts"`
	Interval int       `json:"interval"`
	Point    string    `json:"point"`
	PName    string    `json:"pname"`
	Unit     string    `json:"unit"`
	Region   string    `json:"region"`
	Values   []float64 `json:"values"`
}

type GasBatchAddReply struct {
	Message string `json:"message"`
}
